source 'https://github.com/CocoaPods/Specs.git'

target 'DZQQLib', :exclusive => true do
  pod "DZQQLib", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DZQQLib", :path => "../"

  
end
